/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAmlAlertRequestAttributes struct {
	// Amount
	Amount         Amount  `json:"amount"`
	CreatorDetails Details `json:"creator_details"`
}
