/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type OfferRelationships struct {
	BaseAsset    Relation `json:"base_asset"`
	BaseBalance  Relation `json:"base_balance"`
	Owner        Relation `json:"owner"`
	QuoteAsset   Relation `json:"quote_asset"`
	QuoteBalance Relation `json:"quote_balance"`
}
