/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ChangeRoleRequestRelationships struct {
	AccountToUpdateRole *Relation `json:"account_to_update_role,omitempty"`
}
