/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAtomicSwapRequestOpRelationships struct {
	BaseBalance *Relation `json:"base_balance,omitempty"`
	Bid         *Relation `json:"bid,omitempty"`
	Request     *Relation `json:"request,omitempty"`
}
