/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type LimitsRelationships struct {
	Account *Relation `json:"account,omitempty"`
	Asset   Relation  `json:"asset"`
}
