/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateSaleRequestRelationships struct {
	BaseAsset         Relation           `json:"base_asset"`
	DefaultQuoteAsset Relation           `json:"default_quote_asset"`
	QuoteAssets       RelationCollection `json:"quote_assets"`
}
