/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type PayoutOpAttributes struct {
	ActualFee            Fee    `json:"actual_fee"`
	ActualPayoutAmount   Amount `json:"actual_payout_amount"`
	ExpectedFee          Fee    `json:"expected_fee"`
	MaxPayoutAmount      Amount `json:"max_payout_amount"`
	MinAssetHolderAmount Amount `json:"min_asset_holder_amount"`
}
