/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type AccountRelationships struct {
	Balances          RelationCollection  `json:"balances"`
	ExternalSystemIds *RelationCollection `json:"external_system_ids,omitempty"`
	Fees              *RelationCollection `json:"fees,omitempty"`
	Limits            *RelationCollection `json:"limits,omitempty"`
	Referrer          *Relation           `json:"referrer,omitempty"`
	Role              Relation            `json:"role"`
}
