/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type SignerRoleRelationships struct {
	Owner Relation           `json:"owner"`
	Rules RelationCollection `json:"rules"`
}
