/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ChangeRoleRequestAttributes struct {
	AccountRoleToSet int32   `json:"account_role_to_set"`
	CreatorDetails   Details `json:"creator_details"`
	// Sequence number
	SequenceNumber int32 `json:"sequence_number"`
}
