/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type RemoveExternalSystemPoolOp struct {
	// ID of external system pool
	PoolId int32 `json:"pool_id"`
}
