/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateIssuanceRequestRelationships struct {
	Asset    Relation `json:"asset"`
	Receiver Relation `json:"receiver"`
}
