/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

import (
	"time"
)

type OperationAttributes struct {
	AppliedAt *time.Time `json:"applied_at,omitempty"`
}
