/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAtomicSwapBidRequestAttributes struct {
	// Amount of bid
	BaseAmount     Amount  `json:"base_amount"`
	CreatorDetails Details `json:"creator_details"`
}
