/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreatePreIssuanceRequestOpRelationships struct {
	Asset   *Relation `json:"asset,omitempty"`
	Request *Relation `json:"request,omitempty"`
}
