/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

// Represents a bit mask
type Mask struct {
	Flags *[]MaskFlags `json:"flags,omitempty"`
	// bit mask
	Value *int32 `json:"value,omitempty"`
}
