/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAmlAlertRequestOpAttributes struct {
	Amount         Amount  `json:"amount"`
	CreatorDetails Details `json:"creator_details"`
}
