/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type OperationRelationships struct {
	Details *Relation `json:"details,omitempty"`
	Source  *Relation `json:"source,omitempty"`
	Tx      *Relation `json:"tx,omitempty"`
}
