/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAtomicSwapRequestRelationships struct {
	Bid        Relation `json:"bid"`
	QuoteAsset Relation `json:"quote_asset"`
}
