/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type Links struct {
	Self  *string `json:"Self,omitempty"`
	First *string `json:"First,omitempty"`
	Prev  *string `json:"Prev,omitempty"`
	Next  *string `json:"Next,omitempty"`
	Last  *string `json:"Last,omitempty"`
}
