/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type FeeRecordRelationships struct {
	Account     *Relation `json:"account,omitempty"`
	AccountRole *Relation `json:"account_role,omitempty"`
}
