/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ReviewableRequestRelationships struct {
	RequestDetails Relation `json:"request_details"`
	Requestor      Relation `json:"requestor"`
	Reviewer       Relation `json:"reviewer"`
}
