/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageAssetPairOpRelationships struct {
	BaseAsset  *Relation `json:"base_asset,omitempty"`
	QuoteAsset *Relation `json:"quote_asset,omitempty"`
}
