/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

// Fee - describes fee happened on balance. Direction of fee depends on the operation (depending on effect might be charged, locked, unlocked, for all incoming effects but unlocked it's always charged)
type Fee struct {
	// fixed fee charged for the operation
	Fixed int64 `json:"fixed"`
	// percent of the operation amount
	Percent int64 `json:"percent"`
}
