/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type SaleRequestRelationships struct {
	BaseAsset         *SaleRelationshipsBaseAsset `json:"base_asset,omitempty"`
	DefaultQuoteAsset *Relation                   `json:"default_quote_asset,omitempty"`
	Owner             *SaleRelationshipsOwner     `json:"owner,omitempty"`
	QuoteAssets       *RelationCollection         `json:"quote_assets,omitempty"`
}
