/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type AssetPairRelationships struct {
	BaseAsset  Relation `json:"base_asset"`
	QuoteAsset Relation `json:"quote_asset"`
}
