/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageSignerOpRelationships struct {
	Role   *Relation `json:"role,omitempty"`
	Signer *Relation `json:"signer,omitempty"`
}
