/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageSignerRuleOpRelationships struct {
	Role  *Relation           `json:"role,omitempty"`
	Rules *RelationCollection `json:"rules,omitempty"`
}
