/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAtomicSwapBidRequestOpAttributes struct {
	Amount  *int64   `json:"amount,omitempty"`
	Details *Details `json:"details,omitempty"`
}
