/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ReviewRequestOpRelationships struct {
	RequestDetails *ReviewableRequestDetails `json:"request_details,omitempty"`
}
