/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type SaleQuoteAssetAttributes struct {
	CurrentCap      int64  `json:"current_cap"`
	HardCap         int64  `json:"hard_cap"`
	Price           int64  `json:"price"`
	SoftCap         *int64 `json:"soft_cap,omitempty"`
	TotalCurrentCap int64  `json:"total_current_cap"`
}
