/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageSignerOpAttributes struct {
	Details Details `json:"details"`
	// Weight of the signer fo the account
	Weight int32 `json:"weight"`
}
