/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type AssetPair struct {
	Key
	Attributes    *AssetPairAttributes    `json:"attributes,omitempty"`
	Relationships *AssetPairRelationships `json:"relationships,omitempty"`
}
type AssetPairResponse struct {
	Data     AssetPair `json:"data"`
	Included Included  `json:"included"`
}

type AssetPairsResponse struct {
	Data     []AssetPair `json:"data"`
	Included Included    `json:"included"`
	Links    *Links      `json:"links"`
}

// MustAssetPair - returns AssetPair from include collection.
// if entry with specified key does not exist - returns nil
// if entry with specified key exists but type or ID mismatches - panics
func (c *Included) MustAssetPair(key Key) *AssetPair {
	var assetPair AssetPair
	if c.tryFindEntry(key, &assetPair) {
		return &assetPair
	}
	return nil
}
