/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type Key struct {
	Id   *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
}

func (r *Key) GetKey() Key {
	return *r
}

func (r Key) GetKeyP() *Key {
	return &r
}

func (r Key) AsRelation() *Relation {
	return &Relation{
		Data: r.GetKeyP(),
	}
}
