/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type FeeRecordAttributes struct {
	AppliedTo *FeeAppliedTo `json:"applied_to,omitempty"`
	// Fixed amount to pay
	Fixed int64 `json:"fixed"`
	// Percent to calculate the fee with (e.g., 1.0 represents 100%, 0.21 represents 21%)
	Percent int64 `json:"percent"`
}
