/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type PaymentOpAttributes struct {
	Amount         Amount `json:"amount"`
	DestinationFee Fee    `json:"destination_fee"`
	// Reference for the payment
	Reference string `json:"reference"`
	SourceFee Fee    `json:"source_fee"`
	// Whether source of the payment should pay destination fee
	SourcePayForDestinationFee bool `json:"source_pay_for_destination_fee"`
	// Subject of the payment
	Subject string `json:"subject"`
}
