/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageLimitsRemovalOp struct {
	// ID of limits entry to remove
	LimitsId int32 `json:"limits_id"`
}
