/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreatePreIssuanceRequestRelationships struct {
	Asset CreateAssetRequestRelationshipsAsset `json:"asset"`
}
