/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateExternalSystemPoolOp struct {
	Data string `json:"data"`
	// ID of external system pool
	PoolId int32 `json:"pool_id"`
}
