/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type ManageOfferOpAttributes struct {
	BaseAmount Amount `json:"base_amount"`
	Fee        Fee    `json:"fee"`
	// Offer direction
	IsBuy     bool `json:"is_buy"`
	IsDeleted bool `json:"is_deleted"`
	// ID of the order book
	OrderBookId int32  `json:"order_book_id"`
	Price       Amount `json:"price"`
}
