/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateAtomicSwapBidRequestRelationships struct {
	BaseBalance Relation           `json:"base_balance"`
	QuoteAssets RelationCollection `json:"quote_assets"`
}
