/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

type CreateChangeRoleRequestOpAttributes struct {
	// Tasks for the request
	AllTasks       *int32   `json:"all_tasks,omitempty"`
	CreatorDetails *Details `json:"creator_details,omitempty"`
}
