/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

// Standard JSON:API error
type Errors struct {
	// Non-empty array of errors occurred during request processing
	Errors []ErrorsErrors `json:"errors"`
}
