/*
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package regources

import (
	"time"

	"gitlab.com/tokend/go/xdr"
)

type SaleAttributes struct {
	Details *Details `json:"details,omitempty"`
	// time when the sale expires
	EndTime *time.Time `json:"end_time,omitempty"`
	// state of sale
	SaleState *int32 `json:"sale_state,omitempty"`
	// type of sale
	SaleType *xdr.SaleType `json:"sale_type,omitempty"`
	// time when the sale starts
	StartTime *time.Time `json:"start_time,omitempty"`
}
