config:
  stellar_core_url: http://localhost:8888
  stellar_core_database_url: postgres://core:postgres@localhost:8887/core?sslmode=disable
  hostname: ""
  database_url: postgres://postgres:horizon@localhost:5432/postgres?sslmode=disable
  log_level: "warn"
  slow_query_bound: 1s
  port: 8001
  api_backend: http://
  ingest: true
  stale_threshold: 0
  sign_checkskip: true
  cors_enabled: true
  disable_api_submit: true
  disable_tx_tfa: true
  template_backend: http://
  force_https_links: true
  sentry_dsn: ""
  sentry_log_level: ""
  project: ""
  env: ""
  migrate_up_on_start: true
  cache_period: 5s
  cache_size: 10000
  invest_ready: http://
  telegram_airdrop: http://

cop:
  disabled: true
  endpoint: http://cop
  upstream: http://horizon
  service_name: "horizon-service"
  service_port: "80"
