// Code generated by mockery v1.0.0. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// mockAssetLoader is an autogenerated mock type for the assetLoader type
type mockAssetLoader struct {
	mock.Mock
}

// LoadAsset provides a mock function with given fields: code
func (_m *mockAssetLoader) LoadAsset(code string) (*Asset, error) {
	ret := _m.Called(code)

	var r0 *Asset
	if rf, ok := ret.Get(0).(func(string) *Asset); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Asset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
