// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package cache

import (
	"time"

	"bullioncoin.githost.io/development/horizon/db2/core"
	cache "github.com/patrickmn/go-cache"
)

type CoreAssetAmountCache struct {
	_cache *cache.Cache
}

func newcoreAssetAmountCache(defaultExpiration, cleanupInterval time.Duration) *CoreAssetAmountCache {
	return &CoreAssetAmountCache{
		_cache: cache.New(defaultExpiration, cleanupInterval),
	}
}

func (c *CoreAssetAmountCache) Set(key string, value core.AssetAmount, d time.Duration) {
	c._cache.Set(key, value, d)
}

func (c *CoreAssetAmountCache) Get(k string) (result core.AssetAmount, ok bool) {
	rawResult, ok := c._cache.Get(k)
	if !ok {
		return
	}

	if rawResult == nil {
		return
	}

	result, ok = rawResult.(core.AssetAmount)
	return
}
