// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package cache

import (
	"time"

	"gitlab.com/distributed_lab/tokend/horizon/db2/core"
	cache "github.com/patrickmn/go-cache"
)

type CoreAssetCache struct {
	_cache *cache.Cache
}

func newcoreAssetCache(defaultExpiration, cleanupInterval time.Duration) *CoreAssetCache {
	return &CoreAssetCache{
		_cache: cache.New(defaultExpiration, cleanupInterval),
	}
}

func (c *CoreAssetCache) Set(key string, value core.Asset, d time.Duration) {
	c._cache.Set(key, value, d)
}

func (c *CoreAssetCache) Get(k string) (result core.Asset, ok bool) {
	rawResult, ok := c._cache.Get(k)
	if !ok {
		return
	}

	if rawResult == nil {
		return
	}

	result, ok = rawResult.(core.Asset)
	return
}
