// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package storage

import (
	sq "github.com/lann/squirrel"
	"gitlab.com/distributed_lab/logan"
	"gitlab.com/distributed_lab/logan/v3/errors"
	"gitlab.com/tokend/horizon/db2"
	"gitlab.com/tokend/horizon/db2/history2"
)

type history2ParticipantEffectConvertToValues func(row history2.ParticipantEffect) []interface{}

func history2ParticipantEffectBatchInsert(repo *db2.Repo, rows []history2.ParticipantEffect, tableName string, columns []string, converter history2ParticipantEffectConvertToValues) error {
	if len(rows) == 0 {
		return nil
	}

	sql := sq.Insert(tableName).Columns(columns...)

	paramsInQueue := 0
	for _, row := range rows {
		paramsInQueue += len(columns)
		if paramsInQueue > maxPostgresParams {
			_, err := repo.Exec(sql)
			if err != nil {
				return errors.Wrap(err, "failed to perform batch insert", logan.F{"rows_len": len(rows)})
			}

			sql = sq.Insert(tableName).Columns(columns...)
			paramsInQueue = len(columns)
		}

		sql = sql.Values(converter(row)...)
	}

	if paramsInQueue == 0 {
		return nil
	}

	_, err := repo.Exec(sql)
	if err != nil {
		return errors.Wrap(err, "failed to perform batch insert", logan.F{"rows_len": len(rows)})
	}

	return nil
}
