// Code generated by mockery v1.0.0. DO NOT EDIT.

package changes

import history2 "gitlab.com/tokend/horizon/db2/history2"
import mock "github.com/stretchr/testify/mock"

// mockAssetPairStorage is an autogenerated mock type for the assetPairStorage type
type mockAssetPairStorage struct {
	mock.Mock
}

// InsertAssetPair provides a mock function with given fields: _a0
func (_m *mockAssetPairStorage) InsertAssetPair(_a0 history2.AssetPair) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(history2.AssetPair) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
