// Code generated by mockery v1.0.1. DO NOT EDIT.

package operations

import (
	mock "github.com/stretchr/testify/mock"
	history2 "gitlab.com/tokend/horizon/db2/history2"

	xdr "gitlab.com/tokend/go/xdr"
)

// mockBalanceProvider is an autogenerated mock type for the balanceProvider type
type mockBalanceProvider struct {
	mock.Mock
}

// MustBalance provides a mock function with given fields: balanceID
func (_m *mockBalanceProvider) MustBalance(balanceID xdr.BalanceId) history2.Balance {
	ret := _m.Called(balanceID)

	var r0 history2.Balance
	if rf, ok := ret.Get(0).(func(xdr.BalanceId) history2.Balance); ok {
		r0 = rf(balanceID)
	} else {
		r0 = ret.Get(0).(history2.Balance)
	}

	return r0
}
