// Code generated by mockery v1.0.1. DO NOT EDIT.

package operations

import (
	mock "github.com/stretchr/testify/mock"
	history2 "gitlab.com/tokend/horizon/db2/history2"
)

// mockOperationsStorage is an autogenerated mock type for the operationsStorage type
type mockOperationsStorage struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ops
func (_m *mockOperationsStorage) Insert(ops []history2.Operation) error {
	ret := _m.Called(ops)

	var r0 error
	if rf, ok := ret.Get(0).(func([]history2.Operation) error); ok {
		r0 = rf(ops)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
