// Code generated by mockery v1.0.0. DO NOT EDIT.

package operations

import history2 "gitlab.com/tokend/horizon/db2/history2"
import mock "github.com/stretchr/testify/mock"

// mockSwapProvider is an autogenerated mock type for the swapProvider type
type mockSwapProvider struct {
	mock.Mock
}

// MustSwap provides a mock function with given fields: id
func (_m *mockSwapProvider) MustSwap(id int64) history2.Swap {
	ret := _m.Called(id)

	var r0 history2.Swap
	if rf, ok := ret.Get(0).(func(int64) history2.Swap); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(history2.Swap)
	}

	return r0
}
