// Code generated by mockery v1.0.0. DO NOT EDIT.

package operations

import mock "github.com/stretchr/testify/mock"
import xdr "gitlab.com/tokend/go/xdr"

// mockPublicKeyProvider is an autogenerated mock type for the publicKeyProvider type
type mockPublicKeyProvider struct {
	mock.Mock
}

// GetAccountID provides a mock function with given fields: raw
func (_m *mockPublicKeyProvider) GetAccountID(raw xdr.AccountId) int64 {
	ret := _m.Called(raw)

	var r0 int64
	if rf, ok := ret.Get(0).(func(xdr.AccountId) int64); ok {
		r0 = rf(raw)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetBalanceID provides a mock function with given fields: raw
func (_m *mockPublicKeyProvider) GetBalanceID(raw xdr.BalanceId) int64 {
	ret := _m.Called(raw)

	var r0 int64
	if rf, ok := ret.Get(0).(func(xdr.BalanceId) int64); ok {
		r0 = rf(raw)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
