// Code generated by mockery v1.0.1. DO NOT EDIT.

package operations

import (
	mock "github.com/stretchr/testify/mock"
	history2 "gitlab.com/tokend/horizon/db2/history2"
)

// mockReviewableRequestsStorage is an autogenerated mock type for the reviewableRequestsStorage type
type mockReviewableRequestsStorage struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *mockReviewableRequestsStorage) GetByID(id uint64) (*history2.ReviewableRequest, error) {
	ret := _m.Called(id)

	var r0 *history2.ReviewableRequest
	if rf, ok := ret.Get(0).(func(uint64) *history2.ReviewableRequest); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history2.ReviewableRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
