// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package resources

import (
	"gitlab.com/tokend/go/xdr"
	"gitlab.com/tokend/regources/v2"
)

//FlagFromXdrBlockReasons - unwraps mask into set of flags
func FlagFromXdrBlockReasons(mask int32, allFlags []xdr.BlockReasons) []regources.Flag {
	var result []regources.Flag
	for _, flagValue := range allFlags {
		flagValueAsInt := int32(flagValue)
		if (flagValueAsInt & mask) == flagValueAsInt {
			result = append(result, regources.Flag{
				Value: flagValueAsInt,
				Name:  flagValue.ShortString(),
			})
		}
	}

	return result
}
